# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'Runner' do
  # Use frameworks or modular headers as needed
  use_frameworks!

  # Pods for Runner
  # Flutter automatically manages dependencies for your project.

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      # This line is essential for Flutter plugins to work correctly.
      flutter_additional_ios_build_settings(target)
    end

    ################  Awesome Notifications pod modification  ###################
    awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
    require awesome_pod_file
    update_awesome_pod_build_settings(installer)
    ################  Awesome Notifications pod modification  ###################
  end


################  Awesome Notifications pod modification  ###################
awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
require awesome_pod_file
update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)), flutter_root)
################  Awesome Notifications pod modification  ###################
end

